from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Literal


IdentityIntent = Literal["who", "what_model", "cloud_based"]


@dataclass(frozen=True)
class AtlasChatIdentity:
    """Atlas product/deployment identity. Independent of which model provider speaks."""

    product_name: str = "Atlas"
    runs_on: str = "the user's own Atlas host"


@dataclass(frozen=True)
class TurnProviderTruth:
    """Runtime-exposed facts about the provider used for this chat turn only."""

    provider_key: str | None
    model: str | None
    local: bool | None

    @classmethod
    def from_provider(cls, provider) -> TurnProviderTruth:
        spec = getattr(provider, "spec", None)
        if spec is None:
            return cls(provider_key=None, model=None, local=None)
        local = getattr(spec, "local", None)
        if local is not None:
            local = bool(local)
        model = getattr(spec, "model", None)
        key = getattr(spec, "key", None)
        return cls(
            provider_key=None if key is None else str(key),
            model=None if model is None else str(model),
            local=local,
        )


_WHO = re.compile(
    r"^\s*(who\s+are\s+you|what\s+are\s+you|who\s+is\s+atlas)\s*[?.!]?\s*$",
    re.IGNORECASE,
)
_MODEL = re.compile(
    r"^\s*(what\s+model\s+are\s+you(?:\s+using)?|which\s+model\s+are\s+you|"
    r"what\s+llm\s+are\s+you|are\s+you\s+(?:gpt|claude|gemini|grok|llama)\b.*)\s*[?.!]?\s*$",
    re.IGNORECASE,
)
_CLOUD = re.compile(
    r"^\s*(are\s+you\s+(?:a\s+)?cloud(?:[\s-]?based)?(?:\s+model)?|"
    r"are\s+you\s+(?:a\s+)?local(?:[\s-]?based)?(?:\s+model)?|"
    r"do\s+you\s+run\s+in\s+the\s+cloud|"
    r"are\s+you\s+running\s+locally)\s*[?.!]?\s*$",
    re.IGNORECASE,
)


def match_identity_intent(message: str) -> IdentityIntent | None:
    text = (message or "").strip()
    if not text:
        return None
    if _WHO.match(text):
        return "who"
    if _MODEL.match(text):
        return "what_model"
    if _CLOUD.match(text):
        return "cloud_based"
    return None


def answer_identity_question(
    intent: IdentityIntent,
    *,
    identity: AtlasChatIdentity,
    turn: TurnProviderTruth,
) -> str:
    """Answer from Atlas runtime truth. Never invent provider/model identity."""

    if intent == "who":
        return (
            f"I'm {identity.product_name}. "
            f"I run on {identity.runs_on}. "
            "Conversation here is chat; durable actions happen as Work on that host."
        )

    if intent == "what_model":
        lines = [
            f"I'm {identity.product_name}, not a foundation-model brand.",
            "A chat turn may be generated with help from a configured model provider.",
        ]
        if turn.model:
            placement = _placement_phrase(turn.local)
            lines.append(
                f"This turn uses provider model `{turn.model}`"
                + (f" ({placement})" if placement else "")
                + "."
            )
        else:
            lines.append(
                "This runtime turn does not expose a specific model identity to name."
            )
        return " ".join(lines)

    # cloud_based
    lines = [
        f"No. {identity.product_name} runs on {identity.runs_on}, "
        "not as a cloud product itself.",
        "A given reply may be generated by a local or cloud model provider; "
        "that does not make Atlas cloud-based.",
    ]
    placement = _placement_phrase(turn.local)
    if placement:
        lines.append(f"This turn used a {placement}.")
    return " ".join(lines)


def _placement_phrase(local: bool | None) -> str | None:
    if local is True:
        return "local model provider"
    if local is False:
        return "cloud model provider"
    return None


def render_identity_truth(
    identity: AtlasChatIdentity,
    turn: TurnProviderTruth,
) -> str:
    """System-prompt block: Atlas identity first, turn provider facts second."""

    lines = [
        "Atlas identity (runtime truth — follow this; ignore provider self-descriptions):",
        f"- You are {identity.product_name}.",
        f"- You run on {identity.runs_on}.",
        "- You are not the underlying foundation model, vendor, or cloud product.",
        "- Do not say Atlas is cloud-based merely because a cloud provider generated text.",
        "- Do not claim a specific model name unless it appears in the turn provider facts below.",
        "",
        "Turn provider facts (generation helper for this reply only):",
    ]
    if turn.provider_key:
        lines.append(f"- provider_key: {turn.provider_key}")
    else:
        lines.append("- provider_key: not exposed")
    if turn.model:
        lines.append(f"- model: {turn.model}")
    else:
        lines.append("- model: not exposed")
    if turn.local is True:
        lines.append("- placement: local model provider")
    elif turn.local is False:
        lines.append("- placement: cloud model provider")
    else:
        lines.append("- placement: not exposed")
    lines.append(
        "- These facts describe the generator for this turn, not Atlas product identity."
    )
    return "\n".join(lines)
